spring.application.name=petcarehub-java

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.cache.type=caffeine
spring.cache.cache-names=protocolos,pets,scores
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


SEED_ENABLED=false
app.seed.enabled=true

rsa.public-key=${RSA_PUBLIC_KEY:classpath:Keys/public_key.pem}
rsa.private-key=${RSA_PRIVATE_KEY:classpath:Keys/private_key.pem}